name: Auto Run index.py (Manual Token)

on:
  schedule:
    - cron: "*/5 * * * *"   # AUTO AE tiap 5 menit
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t indexpy .

    - name: Run container (MANUAL TOKEN)
      run: docker run --rm -e BOT_TOKEN=8509612757:AAG1zeVaMoFxGWSqK2eF6NQuUi6hTVjkUXM indexpy
